/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	P:/XIANYU/projects/AnLu/ad_7266_fmc_prj/uisrc/03_ip/rom_ip/singal_rom.v
 ** Date	:	2023 10 20
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module singal_rom ( doa, addra, clka );

	output [7:0] doa;

	input  [9:0] addra;
	input  clka;



	PH1_LOGIC_ERAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(10),
				.DATA_DEPTH_A(1024),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_B(10),
				.DATA_DEPTH_B(1024),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("20K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("../../../fpga_prj_Runs/syn_1/simulation/sin1024.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({8{1'b0}}),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({10{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(1'b0),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule