--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	P:/XIANYU/projects/AnLu/ad_7266_fmc_prj/uisrc/03_ip/rom_ip/singal_rom.vhd
 -- Date	:	2023 10 20
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY singal_rom IS
PORT (
	doa		: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	addra	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	clka		: IN STD_LOGIC
	);
END singal_rom;

ARCHITECTURE struct OF singal_rom IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			ADDR_WIDTH_A	=> 10,
			DATA_DEPTH_A	=> 1024,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_B	=> 10,
			DATA_DEPTH_B	=> 1024,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			IMPLEMENT	=> "20K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../../../fpga_prj_Runs/syn_1/simulation/sin1024.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia		=> (others=>'0'),
			dib		=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea		=> '1',
			ceb		=> '0',
			clka		=> clka,
			clkb		=> '0',
			web		=> '0',
			rsta		=> '0',
			rstb		=> '0',
			doa		=> doa,
			dob		=> OPEN,
			ocea		=> '0',
			oceb		=> '0'
		);

END struct;
